# generated by datamodel-codegen:
#   filename:  action-package.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ComplianceMatrixItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requirement: str
    status: Literal['met', 'missing', 'unclear', 'not_applicable']
    evidence: str | None = None
    next_action: str | None = None
    owner: str | None = None


class RiskRegisterItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    risk: str
    severity: Literal['critical', 'major', 'moderate', 'minor']
    explanation: str | None = None
    mitigation: str | None = None


class TimelineItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: str | None = None
    task: str
    owner: str | None = None


class PartnerSuggestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    partner_type: str
    gap_solved: str
    why_needed: str | None = None
    outreach_angle: str | None = None
    confidence: Literal['high', 'medium', 'low'] | None = None


class OutreachDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str
    body: str


class ActionPackage(BaseModel):
    """
    PRD §8.6 + §10.3 — generate_action_package skill output.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    opportunity_id: UUID
    company_profile_id: UUID
    executive_summary: str
    decision: str
    fit_score: int = Field(..., ge=0, le=100)
    fit_rationale: str
    compliance_matrix: list[ComplianceMatrixItem]
    risk_register: list[RiskRegisterItem]
    proposal_checklist: list[str]
    timeline: list[TimelineItem]
    partner_suggestions: list[PartnerSuggestion] | None = None
    outreach_draft: OutreachDraft | None = None
    approval_required: list[str] = Field(
        ...,
        description='Mirrors §10.3 human_approval_required — items requiring human gate before execution.',
        min_length=1,
    )
    created_at: AwareDatetime
