# generated by datamodel-codegen:
#   filename:  agent-run.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AgentRun(BaseModel):
    """
    PRD §8.7 — one capture run by the agent. `steps` is the trace, `opportunities` the resolved id list.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    profile_id: UUID | None = None
    goal: str = Field(..., min_length=1)
    company_profile_id: UUID | None = None
    status: Literal['pending', 'running', 'complete', 'partial', 'failed']
    steps: list[dict[str, Any]] = Field(
        ...,
        description='Append-only step log; each entry is a TraceEvent or skill-call summary used for replay/audit.',
    )
    opportunities: list[UUID]
    selected_opportunity_id: UUID | None = None
    action_package_id: UUID | None = None
    completed_at: AwareDatetime | None = None
    created_at: AwareDatetime
