# generated by datamodel-codegen:
#   filename:  agent-run-create.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Profile(BaseModel):
    """
    Inline CompanyProfileCreate — used when caller hasn't persisted a profile yet.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    website: str | None = Field(None, max_length=512)
    description: str | None = None
    capabilities: list[str] | None = None
    industry_keywords: list[str] | None = None
    location: str | None = Field(None, max_length=255)
    service_area: list[str] | None = None
    naics_codes: list[str] | None = None
    certifications: list[str] | None = None
    small_business_status: bool | None = None
    sam_status: str | None = Field(None, max_length=64)
    clearance_status: str | None = Field(None, max_length=64)
    past_performance: list[dict[str, Any]] | None = None
    insurance_bonding_status: str | None = Field(None, max_length=255)
    preferred_contract_size: str | None = Field(None, max_length=64)
    preferred_role: Literal['prime', 'sub', 'either'] | None = None


class AgentRunCreate(BaseModel):
    """
    Input shape for POST /agent-runs. Accepts either profile_id (preferred) or inline profile (PRD §9 escape hatch).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    goal: str = Field(..., min_length=1)
    profile_id: UUID | None = None
    profile: Profile | None = Field(
        None,
        description="Inline CompanyProfileCreate — used when caller hasn't persisted a profile yet.",
    )
