# generated by datamodel-codegen:
#   filename:  company-profile-create.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class PastPerformanceItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    title: str
    agency: str | None = None
    value_usd: float | None = None
    year: int | None = None
    summary: str | None = None


class CompanyProfileCreate(BaseModel):
    """
    Input shape for POST /company-profiles. Server-set fields (id, created_at, updated_at) are omitted.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    website: str | None = Field(None, max_length=512)
    description: str | None = None
    capabilities: list[str] | None = []
    industry_keywords: list[str] | None = []
    location: str | None = Field(None, max_length=255)
    service_area: list[str] | None = []
    naics_codes: list[str] | None = []
    certifications: list[str] | None = []
    small_business_status: bool | None = False
    sam_status: str | None = Field(None, max_length=64)
    clearance_status: str | None = Field(None, max_length=64)
    past_performance: list[PastPerformanceItem] | None = Field(
        [], validate_default=True
    )
    insurance_bonding_status: str | None = Field(None, max_length=255)
    preferred_contract_size: str | None = Field(None, max_length=64)
    preferred_role: Literal['prime', 'sub', 'either'] | None = 'either'
