# generated by datamodel-codegen:
#   filename:  company-profile.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class PastPerformanceItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    title: str
    agency: str | None = None
    value_usd: float | None = None
    year: int | None = None
    summary: str | None = None


class CompanyProfile(BaseModel):
    """
    PRD §8.1 — small business profile feeding the capture agent.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    owner_profile_id: UUID | None = None
    name: str = Field(..., max_length=255, min_length=1)
    website: str | None = Field(None, max_length=512)
    description: str | None = None
    capabilities: list[str]
    industry_keywords: list[str]
    location: str | None = Field(None, max_length=255)
    service_area: list[str]
    naics_codes: list[str]
    certifications: list[str]
    small_business_status: bool
    sam_status: str | None = Field(None, max_length=64)
    clearance_status: str | None = Field(None, max_length=64)
    past_performance: list[PastPerformanceItem]
    insurance_bonding_status: str | None = Field(None, max_length=255)
    preferred_contract_size: str | None = Field(None, max_length=64)
    preferred_role: Literal['prime', 'sub', 'either']
    created_at: AwareDatetime
    updated_at: AwareDatetime
