# generated by datamodel-codegen:
#   filename:  competitor-history.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class CompetitorHistory(BaseModel):
    """
    Per-opportunity competitive-intel writeback emitted by Ledger from query_usaspending. One row per (opportunity, owner) per Ledger run.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    opportunity_id: UUID
    owner_profile_id: UUID
    incumbent_name: str | None = None
    awards: list[dict[str, Any]] = Field(
        ...,
        description='Normalized USASpending records: Recipient Name, Award Amount, Period of Performance Start Date, Award ID.',
    )
    total_obligated_usd: float | None = None
    win_difficulty: Literal['easy', 'moderate', 'hard', 'incumbent_lock'] | None = None
    evidence_url: AnyUrl | None = None
    created_at: AwareDatetime
