# generated by datamodel-codegen:
#   filename:  extracted-requirement-create.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ExtractedRequirementCreate(BaseModel):
    """
    POST body for creating an ExtractedRequirement. Server fills id, opportunity_id (from path), and created_at.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal[
        'eligibility',
        'technical',
        'past_performance',
        'certification',
        'insurance',
        'bonding',
        'security',
        'submission',
        'evaluation',
        'deadline',
        'location',
        'pricing',
        'document_required',
    ]
    title: str = Field(..., min_length=1)
    value: str | None = None
    description: str | None = None
    confidence: Literal['high', 'medium', 'low', 'unknown']
    evidence_snippet: str | None = None
    source_document: str | None = None
    page_number: int | None = Field(None, ge=1)
    is_blocker: bool
