# generated by datamodel-codegen:
#   filename:  extracted-requirement.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ExtractedRequirement(BaseModel):
    """
    PRD §8.3 + §10.1 — one structured requirement extracted from a solicitation document.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    opportunity_id: UUID
    type: Literal[
        'eligibility',
        'technical',
        'past_performance',
        'certification',
        'insurance',
        'bonding',
        'security',
        'submission',
        'evaluation',
        'deadline',
        'location',
        'pricing',
        'document_required',
    ]
    title: str = Field(..., min_length=1)
    value: str | None = None
    description: str | None = None
    confidence: Literal['high', 'medium', 'low', 'unknown']
    evidence_snippet: str | None = None
    source_document: str | None = None
    page_number: int | None = Field(None, ge=1)
    is_blocker: bool
    created_at: AwareDatetime
