# generated by datamodel-codegen:
#   filename:  fit-score-create.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Breakdown(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capability: int = Field(..., ge=0, le=20)
    eligibility: int = Field(..., ge=0, le=15)
    naics: int = Field(..., ge=0, le=10)
    past_performance: int = Field(..., ge=0, le=15)
    certification: int = Field(..., ge=0, le=10)
    insurance_bonding: int = Field(..., ge=0, le=10)
    deadline: int = Field(..., ge=0, le=10)
    complexity: int = Field(..., ge=0, le=5)
    geography: int = Field(..., ge=0, le=5)


class FitScoreCreate(BaseModel):
    """
    POST body for creating a FitScore. Server fills id, opportunity_id (from path), and created_at.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    company_profile_id: UUID
    total_score: int = Field(..., ge=0, le=100)
    decision: Literal['strong_pursue', 'pursue', 'maybe', 'reject']
    confidence: Literal['high', 'medium', 'low']
    breakdown: Breakdown
    strengths: list[str]
    weaknesses: list[str]
    blockers: list[str]
    missing_info: list[str]
    recommended_next_action: str | None = None
