# generated by datamodel-codegen:
#   filename:  fit-score.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Breakdown(BaseModel):
    """
    Sub-scores per PRD §5.7 dimensions; sum should equal total_score.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    capability: int = Field(..., ge=0, le=20)
    eligibility: int = Field(..., ge=0, le=15)
    naics: int = Field(..., ge=0, le=10)
    past_performance: int = Field(..., ge=0, le=15)
    certification: int = Field(..., ge=0, le=10)
    insurance_bonding: int = Field(..., ge=0, le=10)
    deadline: int = Field(..., ge=0, le=10)
    complexity: int = Field(..., ge=0, le=5)
    geography: int = Field(..., ge=0, le=5)


class FitScore(BaseModel):
    """
    PRD §8.4 + §10.2 — score_fit skill output, persisted as fit_scores row.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    opportunity_id: UUID
    company_profile_id: UUID
    total_score: int = Field(..., ge=0, le=100)
    decision: Literal['strong_pursue', 'pursue', 'maybe', 'reject']
    confidence: Literal['high', 'medium', 'low']
    breakdown: Breakdown = Field(
        ...,
        description='Sub-scores per PRD §5.7 dimensions; sum should equal total_score.',
    )
    strengths: list[str]
    weaknesses: list[str]
    blockers: list[str]
    missing_info: list[str]
    recommended_next_action: str | None = None
    created_at: AwareDatetime
