# generated by datamodel-codegen:
#   filename:  fixture-manifest.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from api.schemas.opportunity import Opportunity


class FixtureAttachment(BaseModel):
    """Document shipped with a fixture under attachments/."""

    model_config = ConfigDict(
        extra='forbid',
    )
    filename: str
    kind: Literal['solicitation', 'amendment', 'attachment_other']


class FixtureManifest(BaseModel):
    """
    PRD §5.4 — per-fixture metadata consumed by load_seeded_opportunities and the eval harness.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    slug: str = Field(..., pattern=r'^[a-z0-9-]+$', description='Kebab-case identifier; must match the fixture directory name.')
    expected_decision_band: Literal['strong_pursue', 'pursue', 'maybe', 'reject'] = Field(
        ..., description='Expected FitScore decision the agent should produce for this fixture.'
    )
    opportunity: Opportunity = Field(..., description='Full Opportunity record seeded into the DB for this fixture.')
    attachments: list[FixtureAttachment] = Field(..., description='Attachment files shipped with this fixture under attachments/.')
    expected_critical_blockers: list[str] = Field(
        default_factory=list,
        description='Blocker labels the eval harness checks for in ExtractedRequirement rows (is_blocker=true).',
    )
    expected_partner_suggestion: bool = Field(
        False,
        description='Whether the agent is expected to recommend a teaming partner for this fixture.',
    )
