# generated by datamodel-codegen:
#   filename:  fixture-manifest.schema.json

from __future__ import annotations

from datetime import date
from typing import Any, Literal

from pydantic import BaseModel, Field


class Opportunity(BaseModel):
    """
    Opportunity payload passed to load_seeded_opportunities; mirrors the canonical opportunity.schema.json input shape.
    """

    title: str
    agency: str
    solicitation_number: str
    source_url: str | None = None
    due_date: date
    naics: str
    set_aside: str
    place_of_performance: str | None = None
    description: str | None = None
    attachments: list[str] | None = None
    raw_payload: dict[str, Any] | None = None


class Attachment(BaseModel):
    filename: str
    kind: Literal['solicitation', 'amendment', 'attachment_other']


class FixtureManifest(BaseModel):
    """
    Per-fixture metadata used by load_seeded_opportunities and the eval harness.
    """

    slug: str = Field(..., pattern='^[a-z0-9-]+$')
    expected_decision_band: Literal['strong_pursue', 'pursue', 'maybe', 'reject']
    expected_critical_blockers: list[str] | None = None
    expected_partner_suggestion: bool | None = False
    opportunity: Opportunity = Field(
        ...,
        description='Opportunity payload passed to load_seeded_opportunities; mirrors the canonical opportunity.schema.json input shape.',
    )
    attachments: list[Attachment]
