# generated by datamodel-codegen:
#   filename:  opportunity.schema.json

from __future__ import annotations

from datetime import date
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    filename: str
    url: str | None = None
    local_path: str | None = None
    content_type: str | None = None
    bytes: int | None = None


class Opportunity(BaseModel):
    """
    PRD §8.2 — federal opportunity record (live SAM.gov, cached, or seeded fixture).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    title: str = Field(..., min_length=1)
    agency: str
    solicitation_number: str
    source_url: AnyUrl | None = None
    due_date: date | None = None
    naics: str | None = None
    set_aside: str | None = None
    place_of_performance: str | None = None
    description: str | None = None
    attachments: list[Attachment]
    raw_payload: dict[str, Any] | None = Field(
        None,
        description='Verbatim source record (e.g. SAM.gov API row) for audit/debug.',
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime
