# generated by datamodel-codegen:
#   filename:  opportunity.schema.json

from __future__ import annotations

from datetime import date
from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    filename: str
    url: str | None = None
    local_path: str | None = None
    content_type: str | None = None
    bytes: int | None = None


class Opportunity(BaseModel):
    """
    PRD §8.2 — federal opportunity record (live SAM.gov, cached, or seeded fixture).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    slug: str = Field(
        ...,
        description='Stable URL segment; SAM-linked rows often derive from notice id / solicitation.',
        max_length=160,
        min_length=1,
    )
    source_notice_id: str | None = Field(
        None,
        description='SAM.gov notice id when ingested — canonical external key alongside raw_payload.',
        max_length=128,
    )
    title: str = Field(..., min_length=1)
    agency: str
    solicitation_number: str
    notice_type: str | None = Field(
        None, description='SAM notice type / combined synopsis label when available.'
    )
    posted_date: date | None = None
    office_name: str | None = Field(
        None, description='Sub-tier office label (denormalized for list cards).'
    )
    psc_code: str | None = Field(
        None,
        description='PSC text from source (denormalized); optional FK resolution in DB.',
    )
    resource_links: list[str] = Field(
        ..., description='Attachment / resource URLs from SAM resources API.'
    )
    opportunity_status: Literal['open', 'active', 'closed'] = Field(
        ...,
        description='Lifecycle for UI filtering (govbase-style Open/Active/Closed, lowercased).',
    )
    record_kind: Literal['rfp', 'contract'] | None = Field(
        None, description='RFP vs already-awarded contract record when distinguishable.'
    )
    source_url: AnyUrl | None = None
    due_date: date | None = None
    naics: str | None = None
    set_aside: str | None = None
    place_of_performance: str | None = None
    description: str | None = None
    attachments: list[Attachment]
    raw_payload: dict[str, Any] | None = Field(
        None,
        description='Verbatim source record (e.g. SAM.gov API row) for audit/debug.',
    )
    created_at: AwareDatetime
    updated_at: AwareDatetime
