# generated by datamodel-codegen:
#   filename:  risk-flag.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class RiskFlag(BaseModel):
    """
    PRD §8.5 — single risk or blocker emitted by the detect_risks skill.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    opportunity_id: UUID
    company_profile_id: UUID
    category: Literal[
        'clearance_required_unavailable',
        'set_aside_mismatch',
        'certification_gap',
        'past_performance_weakness',
        'deadline_too_close',
        'missing_or_unclear_attachments',
        'submission_ambiguity',
        'insurance_or_bonding_gap',
        'scope_mismatch',
        'legal_compliance_review_required',
        'pricing_complexity',
        'required_document_not_found',
    ]
    severity: Literal['critical', 'major', 'moderate', 'minor']
    title: str = Field(..., min_length=1)
    description: str
    evidence: str | None = None
    mitigation: str | None = None
    requires_human_review: bool
    created_at: AwareDatetime
