# generated by datamodel-codegen:
#   filename:  trace-event.schema.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class RunStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['run_started']
    run_id: UUID
    goal: str
    profile_id: UUID | None = None
    ts: AwareDatetime


class RunCompleted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['run_completed']
    run_id: UUID
    status: Literal['complete', 'partial', 'failed']
    summary: str | None = None
    ts: AwareDatetime


class StepStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['step_started']
    run_id: UUID
    step_id: UUID
    label: str
    ts: AwareDatetime


class StepCompleted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['step_completed']
    run_id: UUID
    step_id: UUID
    status: Literal['complete', 'degraded', 'failed', 'needs_review']
    ts: AwareDatetime


class ToolCalled(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tool_called']
    run_id: UUID
    step_id: UUID
    tool: Literal[
        'parse_goal',
        'search_sam_opportunities',
        'load_seeded_opportunities',
        'rank_opportunities',
        'fetch_attachment',
        'verify_source_page',
        'parse_pdf',
        'extract_requirements',
        'score_fit',
        'detect_risks',
        'generate_action_package',
        'request_human_review',
    ]
    input: dict[str, Any]
    rationale: str | None = None
    ts: AwareDatetime


class ToolReturned(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tool_returned']
    run_id: UUID
    step_id: UUID
    tool: str
    output: dict[str, Any] | None = None
    error: str | None = None
    latency_ms: int = Field(..., ge=0)
    cost_usd: float = Field(..., ge=0.0)
    ts: AwareDatetime


class OpportunityRanked(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['opportunity_ranked']
    run_id: UUID
    opportunity_id: UUID
    score: int = Field(..., ge=0, le=100)
    decision: Literal['strong_pursue', 'pursue', 'maybe', 'reject']
    ts: AwareDatetime


class NeedsHuman(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['needs_human']
    run_id: UUID
    question: str
    context: dict[str, Any] | None = None
    ts: AwareDatetime


class TraceEvent(
    RootModel[
        RunStarted
        | RunCompleted
        | StepStarted
        | StepCompleted
        | ToolCalled
        | ToolReturned
        | OpportunityRanked
        | NeedsHuman
    ]
):
    root: (
        RunStarted
        | RunCompleted
        | StepStarted
        | StepCompleted
        | ToolCalled
        | ToolReturned
        | OpportunityRanked
        | NeedsHuman
    ) = Field(
        ...,
        description='CONTRACTS.md §3 — discriminated union of SSE events emitted on GET /agent-runs/:id/stream.',
        title='TraceEvent',
    )
