"""initial schema

Revision ID: c36679365d34
Revises: 
Create Date: 2026-05-09 06:01:20.570550

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('industry_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('service_area', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('naics_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('small_business_status', sa.Boolean(), nullable=False),
    sa.Column('sam_status', sa.String(length=64), nullable=True),
    sa.Column('clearance_status', sa.String(length=64), nullable=True),
    sa.Column('past_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insurance_bonding_status', sa.String(length=255), nullable=True),
    sa.Column('preferred_contract_size', sa.String(length=64), nullable=True),
    sa.Column('preferred_role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('agency', sa.String(length=255), nullable=False),
    sa.Column('solicitation_number', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('naics', sa.String(length=32), nullable=True),
    sa.Column('set_aside', sa.String(length=128), nullable=True),
    sa.Column('place_of_performance', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_due_date'), 'opportunities', ['due_date'], unique=False)
    op.create_table('action_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('company_profile_id', sa.UUID(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('fit_rationale', sa.Text(), nullable=False),
    sa.Column('compliance_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_register', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposal_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('partner_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outreach_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_required', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=512), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('is_blocker', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_requirements_opportunity_id'), 'extracted_requirements', ['opportunity_id'], unique=False)
    op.create_table('fit_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('company_profile_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_scores_opportunity_id'), 'fit_scores', ['opportunity_id'], unique=False)
    op.create_table('risk_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('company_profile_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_flags_opportunity_id'), 'risk_flags', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_risk_flags_severity'), 'risk_flags', ['severity'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('company_profile_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_opportunity_id', sa.UUID(), nullable=True),
    sa.Column('action_package_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_package_id'], ['action_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_risk_flags_severity'), table_name='risk_flags')
    op.drop_index(op.f('ix_risk_flags_opportunity_id'), table_name='risk_flags')
    op.drop_table('risk_flags')
    op.drop_index(op.f('ix_fit_scores_opportunity_id'), table_name='fit_scores')
    op.drop_table('fit_scores')
    op.drop_index(op.f('ix_extracted_requirements_opportunity_id'), table_name='extracted_requirements')
    op.drop_table('extracted_requirements')
    op.drop_table('action_packages')
    op.drop_index(op.f('ix_opportunities_due_date'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
